import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { TokensArr } from "./options";
import { Manrope } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const manrope = Manrope({
    subsets: ['latin'],
    variable: '--font-manrope',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} h-full antialiased d-none`}
    >
      <body className="min-h-full flex flex-col bg-[#0b1120] font-manrope text-white">
        <Header symbolList={TokensArr}/>
        <div className="px-12">
        {children}
        </div></body>
    </html>
  );
}
